# Generated by Django 3.2.6 on 2021-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'student'), ('1', 'tutor')], default='none', max_length=10),
            preserve_default=False,
        ),
    ]
