# Generated by Django 3.2.6 on 2021-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'student'), ('b', 'tutor')], max_length=10),
        ),
    ]
