# Generated by Django 3.2.6 on 2021-09-19 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectTutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
