# Generated by Django 3.2.6 on 2021-09-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_user_tutsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutSubject',
        ),
    ]
