# Generated by Django 3.2.6 on 2021-09-20 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0009_remove_user_tutsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedSubject', to=settings.AUTH_USER_MODEL),
        ),
    ]
