# Generated by Django 3.2.6 on 2021-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0011_alter_subject_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
