# Generated by Django 3.2.6 on 2021-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
