# Generated by Django 3.2.6 on 2021-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0017_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
